/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PuikButton: typeof import('@prestashopcorp/puik/es')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik/es')['PuikCard']
    PuikCheckbox: typeof import('@prestashopcorp/puik/es')['PuikCheckbox']
    PuikLabel: typeof import('@prestashopcorp/puik/es')['PuikLabel']
    PuikSelect: typeof import('@prestashopcorp/puik/es')['PuikSelect']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
