services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
        restart: always
    work-base:
        image: prestashop/base:7.2-fpm
        depends_on:
            - mysql
    prestashop-run:
        image: prestashop/base:7.2-apache
        user: ${DOCKER_USER_ID:-1000}
        depends_on:
            - mysql
        ports:
            - "8002:80"
        volumes:
            - ./${RELEASE_DIRECTORY}/${BASE_VERSION}:/var/www/html/
    composer:
        image: composer:latest
        volumes:
            - ./:/var/www/html/
