services:
    mysql:
        image: mysql:${MYSQL_TAG}
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: psreference
    shop:
        image: prestashop/prestashop:${PS_TAG}
        volumes:
            - ./autoupgrade:/var/www/html/modules/autoupgrade
            # Comment the next two lines if you don't need xDebug
            - ./build/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./build/init-xdebug.sh:/tmp/init-scripts/init-xdebug.sh
            # Uncomment if you need access to the shop files
            # - ./shopContents:/var/www/html
        environment:
            DB_SERVER: mysql
            DB_PASSWD: root
            DB_NAME: psreference
            PS_DOMAIN: localhost:8001
            PS_INSTALL_AUTO: 1
            PS_ERASE_DB: 1
            PS_INSTALL_DB: 1
            PS_FOLDER_ADMIN: admin-dev
            PS_FOLDER_INSTALL: install-dev
            PS_DEV_MODE: 1
            PS_LANGUAGE: fr
        depends_on:
            - mysql
        ports:
            - "8001:80"
            - "9007:9007"
